# 08 - Transcript cleaning review

Revision de ASR2, desacuerdos, candidatos y policy para decidir E2.

In [1]:
import pandas as pd
from IPython.display import Markdown, display
from data_cleaning.src.transcript_cleaning_review import (
    cargar_outputs, resumen, cambios_por_tipo, usability_counts, disagreement_counts,
    ejemplos_autoaplicados, candidatos_por_tipo, candidatos_no_autoaplicados,
    top_fuentes_problemas, impacto_train, decision,
)
pd.set_option("display.max_colwidth", 180)
changes, candidates, policy, asr2, disagreement = cargar_outputs()

## Resumen

In [2]:
summary = resumen(changes, candidates, policy, asr2, disagreement)
display(summary)

,transcripts,auto_clean_changes,asr2_rows,asr2_ok,asr2_blocked,disagreement_rows,disagreement_high,replacement_candidates,auto_replacements,usable,questionable,bad_candidate,excluded_train
0,5950,52,20,0,20,20,0,48,0,5902,48,0,0

## Current vs ASR2

In [3]:
if asr2.empty:
    display(Markdown("**ASR2 no disponible localmente.**"))
else:
    cols = ["source_id", "clip", "split", "current_text", "asr2_text", "asr2_model", "status", "reason", "asr2_runtime_sec"]
    display(asr2[[c for c in cols if c in asr2.columns]].head(20))

,source_id,clip,split,current_text,asr2_text,asr2_model,status,reason,asr2_runtime_sec
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,test,ok estamos en vivo acabo de subir un video nuevo a mi canal de youtube sobre el curupi,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,test,es un mito paraguayo lo deberian ver,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,test,pero bueno creo que estamos con 7 dias seguidos haciendo lives,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,test,que buena onda espero que la esten disfrutando como yo,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,test,que haces andy todo bien como va la gente mientras todos estan entrando,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,test,queria contarles una anecdota muy graciosa que haces moni que haces rama valen ana,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,test,que buena onda que todos entran asi tan rapido enzo maximo lorito dominic marcelo tuti,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,test,bueno vamos a arrancar con esto les queria contar una anecdota muy graciosa en mi vida,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,test,donde ser argentino o por lo menos mentir y decirles que soy argentino me salvo la vida,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,test,basicamente una vez hace ponele no se 4 o 5 años,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,test,fui a viaje a montreal quebec canada,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,test,donde se habla frances no una ciudad super super linda,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,test,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,test,es espectacular y deberian ir a montreal por favor,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,test,bueno les cuento ni bien llegaba al hotel donde me estaba quedando en montreal con mis amigos,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,test,yo entraba primero mis amigos se quedaron agarraron todas sus valijas y todo,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,test,mientras yo estaba entrando al hotel para subir al lobby y hacer el checkin y todo,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,test,entro al ascensor y entran dos personas mas,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,test,dos tipos que se veian como que si fuesen amigos,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,test,hablando en frances nada mas no completamente en frances,NaN,large-v3-turbo,blocked,blocked_missing_asr_dependency,0.0

## WER/CER current vs ASR2

In [4]:
if disagreement.empty:
    display(Markdown("**Sin disagreement audit disponible.**"))
else:
    display(disagreement_counts(disagreement))
    cols = ["source_id", "clip", "current_text", "asr2_text", "wer_current_vs_asr2", "cer_current_vs_asr2", "token_diff_summary", "disagreement_level", "reasons"]
    display(disagreement[[c for c in cols if c in disagreement.columns]].head(20))

  disagreement_level  clips
0            blocked     20

,source_id,clip,current_text,asr2_text,wer_current_vs_asr2,cer_current_vs_asr2,token_diff_summary,disagreement_level,reasons
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,ok estamos en vivo acabo de subir un video nuevo a mi canal de youtube sobre el curupi,NaN,1.0,1.0,delete: 'ok estamos en vivo acabo de subir un video nuevo a mi canal ' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,es un mito paraguayo lo deberian ver,NaN,1.0,1.0,delete: 'es un mito paraguayo lo deberian ver' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,pero bueno creo que estamos con 7 dias seguidos haciendo lives,NaN,1.0,1.0,delete: 'pero bueno creo que estamos con 7 dias seguidos haciendo liv' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,que buena onda espero que la esten disfrutando como yo,NaN,1.0,1.0,delete: 'que buena onda espero que la esten disfrutando como yo' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,que haces andy todo bien como va la gente mientras todos estan entrando,NaN,1.0,1.0,delete: 'que haces andy todo bien como va la gente mientras todos est' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,queria contarles una anecdota muy graciosa que haces moni que haces rama valen ana,NaN,1.0,1.0,delete: 'queria contarles una anecdota muy graciosa que haces moni qu' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,que buena onda que todos entran asi tan rapido enzo maximo lorito dominic marcelo tuti,NaN,1.0,1.0,delete: 'que buena onda que todos entran asi tan rapido enzo maximo l' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,bueno vamos a arrancar con esto les queria contar una anecdota muy graciosa en mi vida,NaN,1.0,1.0,delete: 'bueno vamos a arrancar con esto les queria contar una anecdo' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,donde ser argentino o por lo menos mentir y decirles que soy argentino me salvo la vida,NaN,1.0,1.0,delete: 'donde ser argentino o por lo menos mentir y decirles que soy' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,basicamente una vez hace ponele no se 4 o 5 años,NaN,1.0,1.0,delete: 'basicamente una vez hace ponele no se 4 o 5 años' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,fui a viaje a montreal quebec canada,NaN,1.0,1.0,delete: 'fui a viaje a montreal quebec canada' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,donde se habla frances no una ciudad super super linda,NaN,1.0,1.0,delete: 'donde se habla frances no una ciudad super super linda' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,NaN,1.0,1.0,delete: 'tengo varios amigos que viven en montreal especialmente en m' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,es espectacular y deberian ir a montreal por favor,NaN,1.0,1.0,delete: 'es espectacular y deberian ir a montreal por favor' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,bueno les cuento ni bien llegaba al hotel donde me estaba quedando en montreal con mis amigos,NaN,1.0,1.0,delete: 'bueno les cuento ni bien llegaba al hotel donde me estaba qu' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,yo entraba primero mis amigos se quedaron agarraron todas sus valijas y todo,NaN,1.0,1.0,delete: 'yo entraba primero mis amigos se quedaron agarraron todas su' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,mientras yo estaba entrando al hotel para subir al lobby y hacer el checkin y todo,NaN,1.0,1.0,delete: 'mientras yo estaba entrando al hotel para subir al lobby y h' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,entro al ascensor y entran dos personas mas,NaN,1.0,1.0,delete: 'entro al ascensor y entran dos personas mas' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,dos tipos que se veian como que si fuesen amigos,NaN,1.0,1.0,delete: 'dos tipos que se veian como que si fuesen amigos' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,hablando en frances nada mas no completamente en frances,NaN,1.0,1.0,delete: 'hablando en frances nada mas no completamente en frances' -> '',blocked,asr2_blocked;blocked_missing_asr_dependency

## Cleaned text y auto-applied replacements

In [5]:
display(cambios_por_tipo(changes))
display(ejemplos_autoaplicados(changes, 15))

           change_type  clips
0  space_normalization     52

,source_id,clip,change_type,evidence,original_text,asr2_text,cleaned_text
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,space_normalization,espacios multiples/strip,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,NaN,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal
69,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0070,space_normalization,espacios multiples/strip,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero,NaN,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero
398,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0286,space_normalization,espacios multiples/strip,yo marcela tauro todo jugo jugo con esa carita,NaN,yo marcela tauro todo jugo jugo con esa carita
492,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0380,space_normalization,espacios multiples/strip,claro esta tu vida vieja y enterrada tus ancestros te la rebaja,NaN,claro esta tu vida vieja y enterrada tus ancestros te la rebaja
832,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0191,space_normalization,espacios multiples/strip,no se fala fala no se no se no digo amigo en que momento entramos a brasil,NaN,no se fala fala no se no se no digo amigo en que momento entramos a brasil
1014,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0056,space_normalization,espacios multiples/strip,es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision,NaN,es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision
1113,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0158,space_normalization,espacios multiples/strip,a lo bueno no le sirve no le sirve a los buenos no les sirve,NaN,a lo bueno no le sirve no le sirve a los buenos no les sirve
1119,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0164,space_normalization,espacios multiples/strip,hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia,NaN,hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia
1125,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0170,space_normalization,espacios multiples/strip,refundemos river pero pero y hoy goza de las mieles de,NaN,refundemos river pero pero y hoy goza de las mieles de
1145,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0192,space_normalization,espacios multiples/strip,de las circunstancias venga merecidisima clasificacion de river,NaN,de las circunstancias venga merecidisima clasificacion de river
1150,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0197,space_normalization,espacios multiples/strip,grave a river hoy en el monumental jugando una semifinal,NaN,grave a river hoy en el monumental jugando una semifinal
1155,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0202,space_normalization,espacios multiples/strip,y bancaste el que te ha hecho y te critiquen bancaste que si echan mal al 9 de racing,NaN,y bancaste el que te ha hecho y te critiquen bancaste que si echan mal al 9 de racing
1163,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0214,space_normalization,espacios multiples/strip,no le da pero no no jugar tener miedo a jugar plantarse tan atras,NaN,no le da pero no no jugar tener miedo a jugar plantarse tan atras
1295,Coronavirus conferencia completa de Alberto Fernán,clip_0158,space_normalization,espacios multiples/strip,estan suspendidas las clases de prensa no el jardin es igual que el nivel primario para ellos es una gran responsabilidad,NaN,estan suspendidas las clases de prensa no el jardin es igual que el nivel primario para ellos es una gran responsabilidad
1373,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,space_normalization,espacios multiples/strip,o o o o o o o o o o yo no encuentro palabras para explicar el fracaso que acaba de hacer boca en la copa libertadores,NaN,o o o o o o o o o o yo no encuentro palabras para explicar el fracaso que acaba de hacer boca en la copa libertadores

## Candidates de reemplazo y desacuerdo

In [6]:
if candidates.empty:
    display(Markdown("**Sin candidates.**"))
else:
    display(candidates.groupby("candidate_type").size().rename("clips").reset_index().sort_values("clips", ascending=False))
    display(candidatos_no_autoaplicados(candidates, 30))

                 candidate_type  clips
0              asr_disagreement     22
2        possible_hallucination     18
1  possible_audio_text_mismatch      8

,source_id,clip,candidate_type,span,suggestion,evidence,confidence,reason_not_auto_applied
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,asr_disagreement,delete: 'ok estamos en vivo acabo de subir un video nuevo a mi canal ' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,asr_disagreement,delete: 'es un mito paraguayo lo deberian ver' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,asr_disagreement,delete: 'pero bueno creo que estamos con 7 dias seguidos haciendo liv' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,asr_disagreement,delete: 'que buena onda espero que la esten disfrutando como yo' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,asr_disagreement,delete: 'que haces andy todo bien como va la gente mientras todos est' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,asr_disagreement,delete: 'queria contarles una anecdota muy graciosa que haces moni qu' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,asr_disagreement,delete: 'que buena onda que todos entran asi tan rapido enzo maximo l' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,asr_disagreement,delete: 'bueno vamos a arrancar con esto les queria contar una anecdo' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,asr_disagreement,delete: 'donde ser argentino o por lo menos mentir y decirles que soy' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,asr_disagreement,delete: 'basicamente una vez hace ponele no se 4 o 5 años' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,asr_disagreement,delete: 'fui a viaje a montreal quebec canada' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,asr_disagreement,delete: 'donde se habla frances no una ciudad super super linda' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,asr_disagreement,delete: 'tengo varios amigos que viven en montreal especialmente en m' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,asr_disagreement,delete: 'es espectacular y deberian ir a montreal por favor' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,asr_disagreement,delete: 'bueno les cuento ni bien llegaba al hotel donde me estaba qu' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,asr_disagreement,delete: 'yo entraba primero mis amigos se quedaron agarraron todas su' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,asr_disagreement,delete: 'mientras yo estaba entrando al hotel para subir al lobby y h' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,asr_disagreement,delete: 'entro al ascensor y entran dos personas mas' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,asr_disagreement,delete: 'dos tipos que se veian como que si fuesen amigos' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,asr_disagreement,delete: 'hablando en frances nada mas no completamente en frances' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,requiere revision humana; no hay evidencia fuerte para reescribir
20,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0097,possible_audio_text_mismatch,yo que se en el pueblo si porque se nota y porque ven los camiones que entran y,NaN,words_per_second=6.93,medium,requiere revision humana; no hay evidencia fuerte para reescribir
21,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0075,possible_hallucination,asi asi asi asi,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
22,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0118,possible_hallucination,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
23,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0266,possible_hallucination,para para para para,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
24,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0281,possible_hallucination,segui segui segui segui,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
25,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0302,possible_hallucination,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
26,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,possible_hallucination,o o o o,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
27,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0086,possible_audio_text_mismatch,porque era el unico grande que jugaba la copa a libertadores porque era el unico,NaN,words_per_second=6.71,medium,requiere revision humana; no hay evidencia fuerte para reescribir
28,Entrevista completa por mi libro Franco con Diego,clip_0395,possible_hallucination,increible increible increible increible,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
29,JULI POGGIO EN FERNÉ CON GREGO,clip_0591,possible_hallucination,ya ya ya ya,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir

## Ejemplos por tipo

In [7]:
for tipo in [
    "entity_replacement_candidate",
    "slang_replacement_candidate",
    "asr_disagreement",
    "possible_hallucination",
    "possible_misalignment",
    "possible_audio_text_mismatch",
]:
    display(Markdown(f"### {tipo}"))
    display(candidatos_por_tipo(candidates, tipo, 8))

### entity_replacement_candidate

Empty DataFrame
Columns: [source_id, clip, candidate_type, span, suggestion, evidence, confidence, current_text, asr2_text, reason_not_auto_applied]
Index: []

### slang_replacement_candidate

Empty DataFrame
Columns: [source_id, clip, candidate_type, span, suggestion, evidence, confidence, current_text, asr2_text, reason_not_auto_applied]
Index: []

### asr_disagreement

,source_id,clip,candidate_type,span,suggestion,evidence,confidence,current_text,asr2_text,reason_not_auto_applied
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,asr_disagreement,delete: 'ok estamos en vivo acabo de subir un video nuevo a mi canal ' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,ok estamos en vivo acabo de subir un video nuevo a mi canal de youtube sobre el curupi,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,asr_disagreement,delete: 'es un mito paraguayo lo deberian ver' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,es un mito paraguayo lo deberian ver,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,asr_disagreement,delete: 'pero bueno creo que estamos con 7 dias seguidos haciendo liv' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,pero bueno creo que estamos con 7 dias seguidos haciendo lives,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,asr_disagreement,delete: 'que buena onda espero que la esten disfrutando como yo' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,que buena onda espero que la esten disfrutando como yo,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,asr_disagreement,delete: 'que haces andy todo bien como va la gente mientras todos est' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,que haces andy todo bien como va la gente mientras todos estan entrando,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,asr_disagreement,delete: 'queria contarles una anecdota muy graciosa que haces moni qu' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,queria contarles una anecdota muy graciosa que haces moni que haces rama valen ana,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,asr_disagreement,delete: 'que buena onda que todos entran asi tan rapido enzo maximo l' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,que buena onda que todos entran asi tan rapido enzo maximo lorito dominic marcelo tuti,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,asr_disagreement,delete: 'bueno vamos a arrancar con esto les queria contar una anecdo' -> '',NaN,level=blocked; reasons=asr2_blocked;blocked_missing_asr_dependency; wer=1.000000; cer=1.000000,low,bueno vamos a arrancar con esto les queria contar una anecdota muy graciosa en mi vida,NaN,requiere revision humana; no hay evidencia fuerte para reescribir

### possible_hallucination

,source_id,clip,candidate_type,span,suggestion,evidence,confidence,current_text,asr2_text,reason_not_auto_applied
21,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0075,possible_hallucination,asi asi asi asi,NaN,mismo token repetido 4 veces,medium,era todo tiempo todo el tiempo era asi asi asi asi,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
22,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0118,possible_hallucination,no no no no,NaN,mismo token repetido 4 veces,medium,y ahi empezo el niño racionador ahi alan dice no no no no estos sandwiches son como,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
23,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0266,possible_hallucination,para para para para,NaN,mismo token repetido 4 veces,medium,no se que le dice digo para para para para digo frena el auto,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
24,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0281,possible_hallucination,segui segui segui segui,NaN,mismo token repetido 4 veces,medium,esta manejando el bueno segui segui segui segui ya esta no soy para nada,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
25,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0302,possible_hallucination,no no no no,NaN,mismo token repetido 4 veces,medium,imaginense marcha atras no no no no yo estaba transpirando porque se nos venian,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
26,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,possible_hallucination,o o o o,NaN,mismo token repetido 4 veces,medium,o o o o o o o o o o yo no encuentro palabras para explicar el fracaso que acaba de hacer boca en la copa libertadores,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
28,Entrevista completa por mi libro Franco con Diego,clip_0395,possible_hallucination,increible increible increible increible,NaN,mismo token repetido 4 veces,medium,gerencia general de fiat italia y conseguimos un contrato increible increible increible increible,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
29,JULI POGGIO EN FERNÉ CON GREGO,clip_0591,possible_hallucination,ya ya ya ya,NaN,mismo token repetido 4 veces,medium,liviana ya ya ya ya esta ayudando decirlo si mas alla de lo que pase despues,NaN,requiere revision humana; no hay evidencia fuerte para reescribir

### possible_misalignment

Empty DataFrame
Columns: [source_id, clip, candidate_type, span, suggestion, evidence, confidence, current_text, asr2_text, reason_not_auto_applied]
Index: []

### possible_audio_text_mismatch

,source_id,clip,candidate_type,span,suggestion,evidence,confidence,current_text,asr2_text,reason_not_auto_applied
20,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0097,possible_audio_text_mismatch,yo que se en el pueblo si porque se nota y porque ven los camiones que entran y,NaN,words_per_second=6.93,medium,yo que se en el pueblo si porque se nota y porque ven los camiones que entran y se entera todo el barrio,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
27,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0086,possible_audio_text_mismatch,porque era el unico grande que jugaba la copa a libertadores porque era el unico,NaN,words_per_second=6.71,medium,porque era el unico grande que jugaba la copa a libertadores porque era el unico grande que jugaba la copa a libertadores,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
31,LA CHABONA X RAMI BILBAO DIVAS DIARY ABITARE 10,clip_0265,possible_audio_text_mismatch,en ganas claro esta en ganas todavia en ganas amor claro o sea todos los dias to,NaN,words_per_second=12.98,medium,en ganas claro esta en ganas todavia en ganas amor claro o sea todos los dias todos los dias todos los dias todos los dias todos los dias todos los dias porque si tu estas e...,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
34,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0034,possible_audio_text_mismatch,que pasan adentro de nuestra cabeza no estoy hablando de un codigo morse sino de,NaN,words_per_second=7.94,medium,que pasan adentro de nuestra cabeza no estoy hablando de un codigo morse sino de una serie de conexiones impulsos tipo codigo morse que pasan adentro de nuestra cabeza no estoy...,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
35,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0143,possible_audio_text_mismatch,le decian opera a este bueno dale ta y el chabon lo unico que le hizo era no se,NaN,words_per_second=8.93,medium,le decian opera a este bueno dale ta y el chabon lo unico que le hizo era no se a la persona que le ponian adelante le decian opera a este bueno dale ta en una gira de 12 dias,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
39,PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias,clip_0055,possible_audio_text_mismatch,y la cubierta es una herramienta que te permite cambiar el neumatico y la barret,NaN,words_per_second=7.87,medium,y la cubierta es una herramienta que te permite cambiar el neumatico y la barretas es una herramienta que te permite cambiar el neumatico que escondemos los bomberos,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
40,Profesiones Argentinas DUEÑOS de SALONES de FIESTA,clip_0004,possible_audio_text_mismatch,quienes somos los dueños de salones,NaN,words_per_second=0.35,medium,quienes somos los dueños de salones,NaN,requiere revision humana; no hay evidencia fuerte para reescribir
42,RIVER GANÓ SUFRIENDO VS CIUDAD DE BOLIVAR!!! ALIVI,clip_0065,possible_audio_text_mismatch,ahora con un partido de un tecnico como michelis ahora con gallardo que hay que,NaN,words_per_second=7.32,medium,ahora con un partido de un tecnico como michelis ahora con gallardo que hay que ver si sos del gusto de gallardo o te ponen porque es lo que hay y a ver si lo salvas,NaN,requiere revision humana; no hay evidencia fuerte para reescribir

## Questionable / bad candidates

In [8]:
display(usability_counts(policy))
display(policy[policy["transcript_usability"].isin(["questionable", "bad_candidate"])].head(30))

  transcript_usability  clips
1               usable   5902
0         questionable     48

,source_id,clip,split,transcript_usability,transcript_reasons,transcript_policy_moderate
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,test,questionable,asr_disagreement,keep
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,test,questionable,asr_disagreement,keep
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,test,questionable,asr_disagreement,keep
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,test,questionable,asr_disagreement,keep
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,test,questionable,asr_disagreement,keep
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,test,questionable,asr_disagreement,keep
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,test,questionable,asr_disagreement,keep
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,test,questionable,asr_disagreement,keep
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,test,questionable,asr_disagreement,keep
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,test,questionable,asr_disagreement,keep
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,test,questionable,asr_disagreement,keep
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,test,questionable,asr_disagreement,keep
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,test,questionable,asr_disagreement,keep
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,test,questionable,asr_disagreement,keep
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,test,questionable,asr_disagreement,keep
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,test,questionable,asr_disagreement,keep
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,test,questionable,asr_disagreement,keep
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,test,questionable,asr_disagreement,keep
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,test,questionable,asr_disagreement,keep
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,test,questionable,asr_disagreement,keep
212,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0097,test,questionable,possible_audio_text_mismatch,keep
732,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0075,train,questionable,possible_hallucination,keep
773,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0118,train,questionable,possible_hallucination,keep
899,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0266,train,questionable,possible_hallucination,keep
914,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0281,train,questionable,possible_hallucination,keep
934,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0302,train,questionable,possible_hallucination,keep
1373,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,train,questionable,possible_hallucination,keep
1451,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0086,train,questionable,possible_audio_text_mismatch,keep
2510,Entrevista completa por mi libro Franco con Diego,clip_0395,train,questionable,possible_hallucination,keep
3110,JULI POGGIO EN FERNÉ CON GREGO,clip_0591,train,questionable,possible_hallucination,keep

## Top source_ids con mas problemas

In [9]:
display(top_fuentes_problemas(policy, 15))

                                             source_id  problem_clips
7      LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91             20
0          ANÉCDOTA VIAJE MUNDIAL BRASIL 2014  parte 1              5
10  Manipulación mental Cómo tu CEREBRO literalmente c              4
1   AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-              3
5                       JULI POGGIO EN FERNÉ CON GREGO              2
8    Las y los estudiantes al frente - Entrevista a la              2
3   DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA              2
6   LA CHABONA X RAMI BILBAO  DIVAS DIARY  ABITARE  10              1
4    Entrevista completa por mi libro Franco con Diego              1
9   ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -              1
2                    CHARLA SOBRE EL AMOR Y EL DESAMOR              1
11  PROFESIONES ARGENTINAS DIRECTORES de CASTING - Tel              1
12  PROFESIONES ARGENTINAS GINECÓLOGOS - Telefe Notici              1
13    PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias              1
14  Profesiones Argentinas DUEÑOS de SALONES de FIESTA              1

## Impacto en train

In [10]:
display(impacto_train(policy))

   train_transcripts  excluded_bad_candidate  kept  excluded_pct
0               4826                       0  4826           0.0

## Decision

In [11]:
display(Markdown("**" + decision(changes, candidates, policy, asr2, disagreement) + "**"))

**BLOCKED_MISSING_ASR2: text-only audit cannot detect hallucinations/misalignment reliably.**