# Batch VSR E0-E4

Tablero de preparacion para los experimentos batch. No entrena modelos, no crea VM y no corre GCP.

In [1]:
import pandas as pd
from IPython.display import Markdown, display

from evaluation.src.batch_vsr_notebook import (
    cargar_configs,
    preprocessing_smoke,
    resultados,
    tamanos_experimentos,
    transcript_asr2,
    transcript_candidates,
    transcript_changes,
    transcript_disagreement,
    transcript_policy,
    transcript_summary,
)

pd.set_option("display.max_colwidth", 140)

## Matriz E0-E4

Revisiones complementarias: `../data_cleaning/notebooks/08_transcript_cleaning_review.ipynb` para cambios/candidatos de transcripts y `../visual_preprocessing/notebooks/09_preprocessing_variant_review.ipynb` para smoke/previews de `lower_face_resized96`.

In [2]:
configs = cargar_configs()
configs[["experiment", "status", "visual_cleaning", "transcript_variant", "preprocessing_variant", "blocked_reason"]]

,experiment,status,visual_cleaning,transcript_variant,preprocessing_variant,blocked_reason
0,E0_baseline_original,ready,none,current,current,
1,E1_visual_cleaned,ready,conservative,current,current,
2,E2_transcript_cleaned_stronger,blocked_missing_asr2,none,transcript_cleaned_stronger,current,falta ASR2 usable; no entrenar E2 como mejora fuerte
3,E3_preprocessing_variant,ready_after_generation,none,current,lower_face_resized96,generar ROIs lower_face_resized96 en VM: evaluation\outputs\batch_vsr\rois_lower_face_resized96
4,E4_all_combined,ready_after_generation,conservative,current,lower_face_resized96,generar ROIs lower_face_resized96 en VM: evaluation\outputs\batch_vsr\rois_lower_face_resized96

In [3]:
tamanos_experimentos(configs)

                       experiment  train  val  test
0            E0_baseline_original   4826  466   658
1               E1_visual_cleaned   4623  466   658
2  E2_transcript_cleaned_stronger   4826  466   658
3        E3_preprocessing_variant   4826  466   658
4                 E4_all_combined   4623  466   658

## Transcript cleaning

In [4]:
changes = transcript_changes()
candidates = transcript_candidates()
policy = transcript_policy()
asr2 = transcript_asr2()
disagreement = transcript_disagreement()
display(transcript_summary(changes, candidates, policy, asr2, disagreement))
if changes.empty:
    display(Markdown("**Pendiente:** no existe `transcript_cleaning_changes.csv`."))
else:
    display(changes[changes["changed"].astype(str).str.lower() == "true"].head(10))
if not disagreement.empty:
    display(disagreement.groupby("disagreement_level").size().rename("clips").reset_index())

,transcripts,changed,unchanged,asr2_ok,disagreement_high,replacement_candidates,auto_replacements,questionable,bad_candidate,decision
0,5950,52,5898,0,0,48,0,48,0,BLOCKED_MISSING_ASR2

,source_id,clip,original_path,cleaned_path,original_text,asr2_text,cleaned_text,changed,change_type,evidence,confidence,auto_applied,asr_disagreement_level
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0013...,evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0013.txt,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,NaN,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,True,space_normalization,espacios multiples/strip,high,True,blocked
69,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0070,C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0070...,evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0070.txt,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero,NaN,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero,True,space_normalization,espacios multiples/strip,high,True,NaN
398,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0286,C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -\clip_0...,evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -\clip_0286.txt,yo marcela tauro todo jugo jugo con esa carita,NaN,yo marcela tauro todo jugo jugo con esa carita,True,space_normalization,espacios multiples/strip,high,True,NaN
492,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0380,C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -\clip_0...,evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -\clip_0380.txt,claro esta tu vida vieja y enterrada tus ancestros te la rebaja,NaN,claro esta tu vida vieja y enterrada tus ancestros te la rebaja,True,space_normalization,espacios multiples/strip,high,True,NaN
832,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0191,C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1\clip_0191.txt,evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1\clip_0191.txt,no se fala fala no se no se no digo amigo en que momento entramos a brasil,NaN,no se fala fala no se no se no digo amigo en que momento entramos a brasil,True,space_normalization,espacios multiples/strip,high,True,NaN
1014,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0056,"C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_00...","evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_0056.txt",es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision,NaN,es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision,True,space_normalization,espacios multiples/strip,high,True,NaN
1113,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0158,"C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_01...","evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_0158.txt",a lo bueno no le sirve no le sirve a los buenos no les sirve,NaN,a lo bueno no le sirve no le sirve a los buenos no les sirve,True,space_normalization,espacios multiples/strip,high,True,NaN
1119,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0164,"C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_01...","evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_0164.txt",hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia,NaN,hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia,True,space_normalization,espacios multiples/strip,high,True,NaN
1125,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0170,"C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_01...","evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_0170.txt",refundemos river pero pero y hoy goza de las mieles de,NaN,refundemos river pero pero y hoy goza de las mieles de,True,space_normalization,espacios multiples/strip,high,True,NaN
1145,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0192,"C:\Users\bianc\NLP Natural Language Processing\labios-argentos-pr24\data\clips\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_01...","evaluation\outputs\batch_vsr\transcripts_cleaned_stronger\AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A\clip_0192.txt",de las circunstancias venga merecidisima clasificacion de river,NaN,de las circunstancias venga merecidisima clasificacion de river,True,space_normalization,espacios multiples/strip,high,True,NaN

  disagreement_level  clips
0            blocked     20

## Preprocessing smoke

In [5]:
smoke = preprocessing_smoke()
if smoke.empty:
    display(Markdown("**Pendiente:** no existe manifest de smoke de preprocessing."))
else:
    display(smoke)

,source_id,clip,original_roi_path,variant_roi_path,variant,shape,dtype,status,reason
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0001.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0001.npz,lower_face_resized96,112x96x96,uint8,ok,NaN
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0002.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0002.npz,lower_face_resized96,81x96x96,uint8,ok,NaN
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0003.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0003.npz,lower_face_resized96,147x96x96,uint8,ok,NaN
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0004.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0004.npz,lower_face_resized96,139x96x96,uint8,ok,NaN
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0005.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0005.npz,lower_face_resized96,137x96x96,uint8,ok,NaN
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0006.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0006.npz,lower_face_resized96,158x96x96,uint8,ok,NaN
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0007.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0007.npz,lower_face_resized96,242x96x96,uint8,ok,NaN
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0008.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0008.npz,lower_face_resized96,154x96x96,uint8,ok,NaN
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0009.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0009.npz,lower_face_resized96,160x96x96,uint8,ok,NaN
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0010.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0010.npz,lower_face_resized96,220x96x96,uint8,ok,NaN
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0011.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0011.npz,lower_face_resized96,136x96x96,uint8,ok,NaN
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0012.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0012.npz,lower_face_resized96,112x96x96,uint8,ok,NaN
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0013.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0013.npz,lower_face_resized96,156x96x96,uint8,ok,NaN
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0014.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0014.npz,lower_face_resized96,110x96x96,uint8,ok,NaN
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0015.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0015.npz,lower_face_resized96,165x96x96,uint8,ok,NaN
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0016.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0016.npz,lower_face_resized96,160x96x96,uint8,ok,NaN
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0017.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0017.npz,lower_face_resized96,140x96x96,uint8,ok,NaN
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0018.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0018.npz,lower_face_resized96,127x96x96,uint8,ok,NaN
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0019.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0019.npz,lower_face_resized96,99x96x96,uint8,ok,NaN
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0020.npz,evaluation\outputs\batch_vsr\preprocessing_variant_smoke\LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91\clip_0020.npz,lower_face_resized96,119x96x96,uint8,ok,NaN

## Resultados VSR

In [6]:
res = resultados()
if res.empty:
    display(Markdown("**Pendiente de VM:** todavia no hay resultados parseados."))
else:
    display(res)

,experiment,status,rows,wer,cer,reason,output
0,E0_baseline_original,pending,NaN,NaN,NaN,falta evaluation\outputs\batch_vsr\raw\E0_baseline_original\test.inf,NaN
1,E1_visual_cleaned,pending,NaN,NaN,NaN,falta evaluation\outputs\batch_vsr\raw\E1_visual_cleaned\test.inf,NaN
2,E2_transcript_cleaned_stronger,pending,NaN,NaN,NaN,falta evaluation\outputs\batch_vsr\raw\E2_transcript_cleaned_stronger\test.inf,NaN
3,E3_preprocessing_variant,pending,NaN,NaN,NaN,falta evaluation\outputs\batch_vsr\raw\E3_preprocessing_variant\test.inf,NaN
4,E4_all_combined,pending,NaN,NaN,NaN,falta evaluation\outputs\batch_vsr\raw\E4_all_combined\test.inf,NaN

In [7]:
ready = configs[configs["status"] == "ready"]["experiment"].tolist()
after = configs[configs["status"] == "ready_after_generation"]["experiment"].tolist()
blocked = configs[configs["status"].astype(str).str.contains("blocked", case=False, na=False)]["experiment"].tolist()
low_impact = configs[configs["status"].astype(str).str.contains("low_impact", case=False, na=False)]["experiment"].tolist()
msg = (
    f"**Ready:** {ready}  " + "\n"
    f"**Ready after generation:** {after}  " + "\n"
    f"**Blocked:** {blocked}  " + "\n"
    f"**Low impact:** {low_impact}"
)
display(Markdown(msg))

**Ready:** ['E0_baseline_original', 'E1_visual_cleaned']
**Ready after generation:** ['E3_preprocessing_variant', 'E4_all_combined']
**Blocked:** ['E2_transcript_cleaned_stronger']
**Low impact:** []