# Transcript Cleaning Review

Revision semantica/operativa de `transcript_cleaned_stronger`. No entrena, no usa VM, no llama LLM.

In [1]:
import pandas as pd
from IPython.display import Markdown, display

from evaluation.src.transcript_cleaning_review import (
    cargar_outputs,
    cambios_por_tipo,
    candidatos_no_autoaplicados,
    decision,
    ejemplos_autoaplicados,
    impacto_train,
    resumen,
    top_fuentes_bad,
    top_fuentes_cambios,
    usability_counts,
)

pd.set_option("display.max_colwidth", 160)
changes, candidates, policy = cargar_outputs()

## Resumen

In [2]:
display(resumen(changes, candidates, policy))
display(usability_counts(policy))

,transcripts,auto_clean_safe_changed,aggressive_candidates,usable,questionable,bad_candidate,excluded_policy_moderate
0,5950,52,29,5921,29,0,0

  transcript_usability  clips
1               usable   5921
0         questionable     29

## Cambios autoaplicados

In [3]:
display(cambios_por_tipo(changes))
display(ejemplos_autoaplicados(changes, 10))

           change_type  clips
0  space_normalization     52

,source_id,clip,change_type,evidence,original_text,cleaned_text
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,space_normalization,espacios multiples/strip,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal,tengo varios amigos que viven en montreal especialmente en montreal especialmente durante el verano en montreal
69,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0070,space_normalization,espacios multiples/strip,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero,que lindo verte aca ah leo le respondo a esta pregunta a sebastian aguero
398,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0286,space_normalization,espacios multiples/strip,yo marcela tauro todo jugo jugo con esa carita,yo marcela tauro todo jugo jugo con esa carita
492,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0380,space_normalization,espacios multiples/strip,claro esta tu vida vieja y enterrada tus ancestros te la rebaja,claro esta tu vida vieja y enterrada tus ancestros te la rebaja
832,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0191,space_normalization,espacios multiples/strip,no se fala fala no se no se no digo amigo en que momento entramos a brasil,no se fala fala no se no se no digo amigo en que momento entramos a brasil
1014,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0056,space_normalization,espacios multiples/strip,es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision,es muy dificil es mucha ventaja es mucha ventaja lo del arbitro fue realmente impresentable en esa decision
1113,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0158,space_normalization,espacios multiples/strip,a lo bueno no le sirve no le sirve a los buenos no les sirve,a lo bueno no le sirve no le sirve a los buenos no les sirve
1119,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0164,space_normalization,espacios multiples/strip,hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia,hace cuatro meses estaba con el boleto a santiago del estero y que le importa que me importaba la mitologia
1125,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0170,space_normalization,espacios multiples/strip,refundemos river pero pero y hoy goza de las mieles de,refundemos river pero pero y hoy goza de las mieles de
1145,"AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A",clip_0192,space_normalization,espacios multiples/strip,de las circunstancias venga merecidisima clasificacion de river,de las circunstancias venga merecidisima clasificacion de river

## Candidatos no autoaplicados

In [4]:
if candidates.empty:
    display(Markdown("No hay candidatos agresivos pendientes."))
else:
    display(candidates.groupby("candidate_type").size().rename("clips").reset_index().sort_values("clips", ascending=False))
    display(candidatos_no_autoaplicados(candidates, 30))

           candidate_type  clips
0    anomalous_repetition     18
4   too_long_for_duration      7
1     consonant_run_token      1
2   long_suspicious_token      1
3    rare_character_token      1
5  too_short_for_duration      1

,source_id,clip,candidate_type,span,suggestion,evidence,confidence,reason_not_auto_applied
0,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0097,too_long_for_duration,yo que se en el pueblo si porque se nota y porque ven los camiones que entran y,NaN,words_per_second=6.93,medium,requiere revision humana; no hay evidencia fuerte para reescribir
1,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0075,anomalous_repetition,asi asi asi asi,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
2,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0118,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
3,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0266,anomalous_repetition,para para para para,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
4,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0281,anomalous_repetition,segui segui segui segui,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
5,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0302,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
6,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,anomalous_repetition,o o o o,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
7,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0086,too_long_for_duration,porque era el unico grande que jugaba la copa a libertadores porque era el unico,NaN,words_per_second=6.71,medium,requiere revision humana; no hay evidencia fuerte para reescribir
8,Entrevista completa por mi libro Franco con Diego,clip_0395,anomalous_repetition,increible increible increible increible,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
9,JULI POGGIO EN FERNÉ CON GREGO,clip_0591,anomalous_repetition,ya ya ya ya,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
10,JULI POGGIO EN FERNÉ CON GREGO,clip_0592,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
11,LA CHABONA X RAMI BILBAO DIVAS DIARY ABITARE 10,clip_0265,too_long_for_duration,en ganas claro esta en ganas todavia en ganas amor claro o sea todos los dias to,NaN,words_per_second=12.98,medium,requiere revision humana; no hay evidencia fuerte para reescribir
12,Las y los estudiantes al frente - Entrevista a la,clip_0185,rare_character_token,Zhu,NaN,caracter fuera del set esperado,medium,requiere revision humana; no hay evidencia fuerte para reescribir
13,Las y los estudiantes al frente - Entrevista a la,clip_0257,anomalous_repetition,por por por por,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
14,Los lujos de L-Gante y qué aprendió cuando estuvo,clip_0073,consonant_run_token,chrysler,NaN,racha consonantica 6+,low,requiere revision humana; no hay evidencia fuerte para reescribir
15,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0034,too_long_for_duration,que pasan adentro de nuestra cabeza no estoy hablando de un codigo morse sino de,NaN,words_per_second=7.94,medium,requiere revision humana; no hay evidencia fuerte para reescribir
16,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0143,too_long_for_duration,le decian opera a este bueno dale ta y el chabon lo unico que le hizo era no se,NaN,words_per_second=8.93,medium,requiere revision humana; no hay evidencia fuerte para reescribir
17,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0146,anomalous_repetition,ta ta ta ta,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
18,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0150,anomalous_repetition,ta ta ta ta,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
19,PROFESIONES ARGENTINAS DIRECTORES de CASTING - Tel,clip_0039,anomalous_repetition,tal tal tal tal,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
20,PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias,clip_0055,too_long_for_duration,y la cubierta es una herramienta que te permite cambiar el neumatico y la barret,NaN,words_per_second=7.87,medium,requiere revision humana; no hay evidencia fuerte para reescribir
21,Profesiones Argentinas DUEÑOS de SALONES de FIESTA,clip_0004,too_short_for_duration,quienes somos los dueños de salones,NaN,words_per_second=0.35,medium,requiere revision humana; no hay evidencia fuerte para reescribir
22,Profesiones Argentinas PERIODISTAS DEPORTIVOS - Te,clip_0100,anomalous_repetition,tac tac tac tac,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
23,RIVER GANÓ SUFRIENDO VS CIUDAD DE BOLIVAR!!! ALIVI,clip_0065,too_long_for_duration,ahora con un partido de un tecnico como michelis ahora con gallardo que hay que,NaN,words_per_second=7.32,medium,requiere revision humana; no hay evidencia fuerte para reescribir
24,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0030,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
25,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0039,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
26,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0191,anomalous_repetition,no no no no,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
27,CHARLA SOBRE EL AMOR Y EL DESAMOR,clip_0112,anomalous_repetition,amas amas amas amas,NaN,mismo token repetido 4 veces,medium,requiere revision humana; no hay evidencia fuerte para reescribir
28,PROFESIONES ARGENTINAS GINECÓLOGOS - Telefe Notici,clip_0010,long_suspicious_token,poliposandometriales,NaN,token_len=20,medium,requiere revision humana; no hay evidencia fuerte para reescribir

## Bad candidates / review

In [5]:
display(policy[policy["transcript_usability"].isin(["questionable", "bad_candidate"])].head(30))
display(top_fuentes_bad(policy))

,source_id,clip,split,transcript_usability,transcript_reasons,transcript_policy_moderate
212,ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -,clip_0097,test,questionable,too_long_for_duration,keep
732,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0075,train,questionable,anomalous_repetition,keep
773,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0118,train,questionable,anomalous_repetition,keep
899,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0266,train,questionable,anomalous_repetition,keep
914,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0281,train,questionable,anomalous_repetition,keep
934,ANÉCDOTA VIAJE MUNDIAL BRASIL 2014 parte 1,clip_0302,train,questionable,anomalous_repetition,keep
1373,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0008,train,questionable,anomalous_repetition,keep
1451,DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA,clip_0086,train,questionable,too_long_for_duration,keep
2510,Entrevista completa por mi libro Franco con Diego,clip_0395,train,questionable,anomalous_repetition,keep
3110,JULI POGGIO EN FERNÉ CON GREGO,clip_0591,train,questionable,anomalous_repetition,keep
3111,JULI POGGIO EN FERNÉ CON GREGO,clip_0592,train,questionable,anomalous_repetition,keep
3176,LA CHABONA X RAMI BILBAO DIVAS DIARY ABITARE 10,clip_0265,train,questionable,too_long_for_duration,keep
3361,Las y los estudiantes al frente - Entrevista a la,clip_0185,train,questionable,rare_character_token,keep
3432,Las y los estudiantes al frente - Entrevista a la,clip_0257,train,questionable,anomalous_repetition,keep
3589,Los lujos de L-Gante y qué aprendió cuando estuvo,clip_0073,train,questionable,consonant_run_token,keep
3731,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0034,train,questionable,too_long_for_duration,keep
3840,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0143,train,questionable,too_long_for_duration,keep
3843,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0146,train,questionable,anomalous_repetition,keep
3847,Manipulación mental Cómo tu CEREBRO literalmente c,clip_0150,train,questionable,anomalous_repetition,keep
4017,PROFESIONES ARGENTINAS DIRECTORES de CASTING - Tel,clip_0039,train,questionable,anomalous_repetition,keep
4199,PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias,clip_0055,train,questionable,too_long_for_duration,keep
4801,Profesiones Argentinas DUEÑOS de SALONES de FIESTA,clip_0004,train,questionable,too_short_for_duration,keep
5095,Profesiones Argentinas PERIODISTAS DEPORTIVOS - Te,clip_0100,train,questionable,anomalous_repetition,keep
5246,RIVER GANÓ SUFRIENDO VS CIUDAD DE BOLIVAR!!! ALIVI,clip_0065,train,questionable,too_long_for_duration,keep
5509,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0030,val,questionable,anomalous_repetition,keep
5518,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0039,val,questionable,anomalous_repetition,keep
5644,AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-,clip_0191,val,questionable,anomalous_repetition,keep
5751,CHARLA SOBRE EL AMOR Y EL DESAMOR,clip_0112,val,questionable,anomalous_repetition,keep
5886,PROFESIONES ARGENTINAS GINECÓLOGOS - Telefe Notici,clip_0010,val,questionable,long_suspicious_token,keep

Empty DataFrame
Columns: [source_id, bad_candidate]
Index: []

## Ejemplos por fuente

In [6]:
display(top_fuentes_cambios(changes))
if not candidates.empty:
    display(candidates.groupby("source_id").size().rename("candidates").reset_index().sort_values("candidates", ascending=False).head(15))

                                             source_id  changed
2    AZZARO REACCIÓN - RIVER, A LA FINAL LE GANÓ 1-0 A        8
5                       JULI POGGIO EN FERNÉ CON GREGO        7
14  Por qué ya no podemos conversar (y cómo aprender a        7
8    Las y los estudiantes al frente - Entrevista a la        6
9    Los lujos de L-Gante y qué aprendió cuando estuvo        3
4   DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA        3
1   AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-        3
16  Profesiones Argentinas EMPLEADOS de PANADERÍAS - T        2
7      LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91        2
10  ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -        2
13    PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias        1
17  Profesiones Argentinas PERIODISTAS DEPORTIVOS - Te        1
15  Profesiones Argentinas DUEÑOS de SALONES de FIESTA        1
0          ANÉCDOTA VIAJE MUNDIAL BRASIL 2014  parte 1        1
12  PROFESIONES ARGENTINAS FARMACÉUTICOS - Telefe Noti        1

                                             source_id  candidates
0          ANÉCDOTA VIAJE MUNDIAL BRASIL 2014  parte 1           5
10  Manipulación mental Cómo tu CEREBRO literalmente c           4
1   AZZARO REACCIÓN - CICLO TERMINADO RACING EMPATÓ 2-           3
3   DAVOO XENEIZE OPINA DE BOCA 0 UNIVERSIDAD CATOLICA           2
5                       JULI POGGIO EN FERNÉ CON GREGO           2
7    Las y los estudiantes al frente - Entrevista a la           2
11  PROFESIONES ARGENTINAS DIRECTORES de CASTING - Tel           1
15  Profesiones Argentinas PERIODISTAS DEPORTIVOS - Te           1
14  Profesiones Argentinas DUEÑOS de SALONES de FIESTA           1
13    PROFESIONES ARGENTINAS GOMEROS - Telefe Noticias           1
12  PROFESIONES ARGENTINAS GINECÓLOGOS - Telefe Notici           1
8    Los lujos de L-Gante y qué aprendió cuando estuvo           1
9   ME ACUSARON DE BRUJA Y ME TUVE QUE IR DEL PUEBLO -           1
6   LA CHABONA X RAMI BILBAO  DIVAS DIARY  ABITARE  10           1
4    Entrevista completa por mi libro Franco con Diego           1

## Impacto esperado en train

In [7]:
display(impacto_train(policy))

   train_transcripts  excluded_bad_candidate  kept  excluded_pct
0               4826                       0  4826           0.0

## Decision: listo / revisar / bloquear

In [8]:
display(Markdown(decision(changes, candidates, policy)))

revisar: hay candidatos agresivos y/o bad_candidate antes de correr VM.