# 09 - Preprocessing variant review

Revision de `lower_face_resized96` antes de generar ROIs full en VM.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import Image, Markdown, display
from visual_preprocessing.src.preprocessing_variant_review import (
    cargar_smoke, cargar_full, full_generation_status, pending_message,
    preview_groups, preview_paths, sample_table, smoke_decision, smoke_status,
)
pd.set_option("display.max_colwidth", 160)
smoke = cargar_smoke()
full = cargar_full()
status = smoke_status(smoke)
decision = smoke_decision(smoke)

## Smoke readiness

In [2]:
display(pd.DataFrame([{"variant": "lower_face_resized96", "smoke_status": status, "decision": decision, "clips": len(smoke)}]))
display(Markdown(pending_message(status, decision)))

                variant smoke_status                   decision  clips
0  lower_face_resized96    generated  READY_FOR_FULL_GENERATION     20

Smoke generado: revisar grillas y shapes antes de VM full.

## Smoke manifest

In [3]:
display(sample_table(smoke).head(25))

,source_id,clip,current_shape,variant_shape,dtype,frame_count,status,reason
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,,,,0,ok,NaN
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,,,,0,ok,NaN
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,,,,0,ok,NaN
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,,,,0,ok,NaN
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,,,,0,ok,NaN
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,,,,0,ok,NaN
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,,,,0,ok,NaN
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,,,,0,ok,NaN
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,,,,0,ok,NaN
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,,,,0,ok,NaN
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,,,,0,ok,NaN
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,,,,0,ok,NaN
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,,,,0,ok,NaN
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,,,,0,ok,NaN
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,,,,0,ok,NaN
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,,,,0,ok,NaN
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,,,,0,ok,NaN
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,,,,0,ok,NaN
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,,,,0,ok,NaN
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,,,,0,ok,NaN

## Full generation manifest

In [4]:
display(full_generation_status(full))
if not full.empty:
    display(full.head(20))

   full_rows    ok  failed  blocked status
0       5950  5950       0        0  ready

,source_id,clip,original_roi_path,variant_roi_path,variant,shape,dtype,status,reason
0,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0001,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0001.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0001.npz,lower_face_resized96,112x96x96,uint8,ok,NaN
1,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0002,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0002.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0002.npz,lower_face_resized96,81x96x96,uint8,ok,NaN
2,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0003,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0003.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0003.npz,lower_face_resized96,147x96x96,uint8,ok,NaN
3,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0004,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0004.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0004.npz,lower_face_resized96,139x96x96,uint8,ok,NaN
4,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0005,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0005.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0005.npz,lower_face_resized96,137x96x96,uint8,ok,NaN
5,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0006,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0006.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0006.npz,lower_face_resized96,158x96x96,uint8,ok,NaN
6,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0007,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0007.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0007.npz,lower_face_resized96,242x96x96,uint8,ok,NaN
7,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0008,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0008.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0008.npz,lower_face_resized96,154x96x96,uint8,ok,NaN
8,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0009,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0009.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0009.npz,lower_face_resized96,160x96x96,uint8,ok,NaN
9,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0010,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0010.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0010.npz,lower_face_resized96,220x96x96,uint8,ok,NaN
10,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0011,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0011.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0011.npz,lower_face_resized96,136x96x96,uint8,ok,NaN
11,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0012,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0012.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0012.npz,lower_face_resized96,112x96x96,uint8,ok,NaN
12,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0013,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0013.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0013.npz,lower_face_resized96,156x96x96,uint8,ok,NaN
13,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0014,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0014.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0014.npz,lower_face_resized96,110x96x96,uint8,ok,NaN
14,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0015,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0015.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0015.npz,lower_face_resized96,165x96x96,uint8,ok,NaN
15,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0016,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0016.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0016.npz,lower_face_resized96,160x96x96,uint8,ok,NaN
16,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0017,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0017.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0017.npz,lower_face_resized96,140x96x96,uint8,ok,NaN
17,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0018,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0018.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0018.npz,lower_face_resized96,127x96x96,uint8,ok,NaN
18,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0019,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0019.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0019.npz,lower_face_resized96,99x96x96,uint8,ok,NaN
19,LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91,clip_0020,data/processed/lip_rois/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0020.npz,evaluation/outputs/batch_vsr/rois_lower_face_resized96/LE DIJE QUE SOY ARGENTINO - Story Time - CAP 91/clip_0020.npz,lower_face_resized96,119x96x96,uint8,ok,NaN

## Preview paths

In [5]:
groups = preview_groups()
display(groups.head(20))

Empty DataFrame
Columns: []
Index: []

## Preview render

In [6]:
paths = preview_paths()
for path in paths["path"].head(3) if not paths.empty else []:
    display(Markdown(f"`{path}`"))
    display(Image(filename=path))